obj-$(CONFIG_PM8921_BMS_XIAOMI) += bms-batterydata.o \
	bms-batterydata-desay.o \
	bms-batterydata-sony.o \
	bms-batterydata-samsung.o \
	bms-batterydata-lg.o \
	bms-batterydata-lg-3000.o \
	bms-batterydata-sony-3000.o \
	bms-batterydata-samsung-3000.o \
	bms-batterydata-samsung-2000.o \
	bms-batterydata-lg-2000.o
