obj-$(CONFIG_MACH_APQ8064_ARIES) += \
	board-aries.o \
	board-aries-display.o \
	board-aries-input.o \
	board-aries-sound.o \
	board-aries-camera.o

CFLAGS_board-aries-display.o += -Idrivers/video -Idrivers/video/msm
