GCC_VERSION      := $(shell $(CONFIG_SHELL) $(PWD)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)
ccflags-y += -Idrivers/media/video/msm_aries
ccflags-y += -Idrivers/media/video/msm_aries/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o

